In [1]:
from fastai.vision import *
from fastai.metrics import accuracy

In [2]:
defaults.device = torch.device('cpu')

In [3]:
learn = load_learner('D:/Downloads/')

In [4]:
import cv2

In [5]:
cap = cv2.VideoCapture(0)
message = ' '
frame_interval = 10
frame_count = 0
pred = []
green = (0, 255, 0)
red = (0, 0, 255)
while True:
    ret, frame = cap.read()
    frame_count += 1
    img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = Image(pil2tensor(img, dtype=np.float32).div_(255))
    pred_class, pred_idx, outputs = learn.predict(img)
    if (frame_count % frame_interval) == 0:
        letter = max(set(pred), key=pred.count)
        if letter == 'nothing':
            pass
        elif letter == 'space':
            message += ' '
        elif letter == 'del':
            message = message[:-1]  
        else:
            message += letter
        pred = []
    else:
        pred.append(str(pred_class))
    cv2.putText(frame, str(pred_class)+' prob: '+str(outputs[pred_idx])[7:-1], (100, 400), cv2.FONT_HERSHEY_SIMPLEX, 1, red, thickness=2, lineType=2)
    cv2.putText(frame, message, (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, green, thickness=2, lineType=2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows() 

In [6]:
print(message)

YYNNTPPPPYQQLPPWCBCQQCIISBO


In [7]:
# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows() 

In [8]:
frame.shape

(480, 640, 3)

In [9]:
max(set(pred), key=pred.count)

'N'

In [10]:
pred

['N', 'N']

In [11]:
outputs

tensor([5.2085e-31, 3.8421e-25, 4.2002e-29, 1.5965e-34, 6.4472e-07, 7.3444e-31,
        5.9175e-15, 1.4025e-23, 3.6465e-25, 2.5195e-32, 2.3788e-33, 3.0840e-12,
        8.0138e-01, 4.1583e-12, 1.3005e-18, 6.7386e-15, 3.8266e-28, 1.9861e-01,
        4.4475e-14, 2.9063e-25, 4.8465e-15, 4.0899e-07, 1.8948e-15, 1.1043e-24,
        1.3162e-10, 2.4400e-27, 3.0386e-21])

In [12]:
outputs

tensor([5.2085e-31, 3.8421e-25, 4.2002e-29, 1.5965e-34, 6.4472e-07, 7.3444e-31,
        5.9175e-15, 1.4025e-23, 3.6465e-25, 2.5195e-32, 2.3788e-33, 3.0840e-12,
        8.0138e-01, 4.1583e-12, 1.3005e-18, 6.7386e-15, 3.8266e-28, 1.9861e-01,
        4.4475e-14, 2.9063e-25, 4.8465e-15, 4.0899e-07, 1.8948e-15, 1.1043e-24,
        1.3162e-10, 2.4400e-27, 3.0386e-21])

In [13]:
max(outputs)

tensor(0.8014)

In [14]:
outputs[pred_idx]

tensor(0.8014)

In [93]:
message = ' '
frame_interval = 10
frame_count = 0
pred = []
green = (0, 255, 0)
red = (0, 0, 255)

cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    frame_count += 1
    
#     hand_cascade = cv2.CascadeClassifier('D:/College/Sem VI/CV/aGest.xml')
#     hand_rect = hand_cascade.detectMultiScale(frame, scaleFactor = 1.2, minNeighbors = 5)
#     for (x, y, w, h) in hand_rect: 
#         cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 255, 255), 10)
#     cv2.imshow('crop', frame[y:y+h, x:x+w])
#     frame[y:y+h, x:x+w]
    
    img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = Image(pil2tensor(img, dtype=np.float32).div_(255))
    pred_class, pred_idx, outputs = learn.predict(img)
    
    if (frame_count % frame_interval) == 0:
        letter = max(set(pred), key=pred.count)
        if letter == 'nothing':
            pass
        elif letter == 'space':
            message += ' '
        elif letter == 'del':
            message = message[:-1]  
        else:
            message += letter
        pred = []
    else:
        pred.append(str(pred_class))
    
    cv2.putText(frame, str(pred_class)+' prob: '+str(outputs[pred_idx])[7:-1], (100, 400), cv2.FONT_HERSHEY_SIMPLEX, 1, red, thickness=2, lineType=2)
    cv2.putText(frame, message, (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, green, thickness=2, lineType=2)
    cv2.imshow('Video', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows() 

In [84]:
frame = cv2.imread('D:/College/Sem VI/CV/download (2).jfif')
cv2.imshow('orig', frame)
hand_cascade = cv2.CascadeClassifier('D:/College/Sem VI/CV/haarcascade_frontalface_alt2.xml')
hand_rect = hand_cascade.detectMultiScale(frame, scaleFactor=1.2, minNeighbors=5)
for (x, y, w, h) in hand_rect: 
    cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 255, 255), 10)
    cv2.imshow('crop', frame[y:y+h, x:x+w])
cv2.imshow('detected', frame)
cv2.waitKey()

# frame[y:y+h, x:x+w]
# if cv2.waitKey(1) & 0xFF == ord('q'):
#     pass

113

In [85]:
hand_rect

array([[ 14,  51, 156, 156]], dtype=int32)

In [82]:
hand_cascade

<CascadeClassifier 00000204A29D1990>

In [86]:
cv2.destroyAllWindows()

In [92]:
str(outputs[pred_idx])[7:-1]

'1.0000'

In [94]:
print(message)

MMIIXXXLLYYY
